host_user_name:
ssh_private_key_file:
ssh_public_key_file:

pi_host:
pi_hostname:
pi_user_name:
# The password must be hashed
# From a Linux terminal, run `mkpasswd --method=SHA-512`
# and enter the password when prompted. Copy and past the result below.
pi_user_pass:

